### ISSUE TITLE
[Suggestion] Page title emojis

### ISSUE THREAD

**Issue by cclypeatus** [dndworld/dndworld.github.io#9]
We could set up the emojis placed before the page's titles to not show up on the tab by adding them with a snippet like this:

```md
<style>
  h1:before { content: "👋 " }
</style>
```

**Comment by dndworld** [comment]
Sounds good

**Comment by cclypeatus** [comment]
Implemented with dc03a3b57c2de71bac8a8dde68b62008214dd59f
